version: "3.8"

services:
  db_primary:
    image: postgres:15
    environment:
      POSTGRES_DB: bubbleshot_inst_2
      POSTGRES_USER: bubbleshot
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  db_standby:
    image: postgres:15
    environment:
      POSTGRES_DB: bubbleshot_inst_2
      POSTGRES_USER: bubbleshot
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
